### ISSUE TITLE
Kick-off Feedback

### ISSUE THREAD

**Issue by emilybandfield** [beginally/data-analyst#5]
Great job, @thedatadavis ! You don't suck! I learned things! 

**Information**
- List of terms used in the course might be helpful (things like "repro", "CSV") to start with (even if it's a list that people study on their own, or a supplemental material for those who need it)
- Overview of Github + Sheets for those who are unfamiliar (optional pre-recorded videos before first session available to students?)
- Survey of comfort level in Excel + Sheets beforehand

**Presentation**
- Be intentional about really looking at the camera when you're speaking to students, vs looking away at your other screen when you're screen sharing
- Clearer separation of times when you're instructing vs letting students work on their own. I found myself distracted when trying to complete the task if you started talking again before I was finished :) 
- Figure out a way for students to let you know they've completed a task. Maybe it is just everyone saying "I'm finished" or maybe we get creative to make it more streamlined especially when there are more people at once.
- Provide plenty of specific opportunities for students to ask questions, so they don't feel like they're interrupting "Does anyone have any questions before we move on?"

**Comment by thedatadavis** [comment]
> **Information**
> * List of terms used in the course might be helpful (things like "repro", "CSV") to start with (even if it's a list that people study on their own, or a supplemental material for those who need it)
> * Overview of Github + Sheets for those who are unfamiliar (optional pre-recorded videos before first session available to students?)
> * Survey of comfort level in Excel + Sheets beforehand

Extremely valid feedback. I'm currently thinking through which level of "pre-work" would be useful to help people get grounded beforehand. Will be managing these in this [project board](https://github.com/beginally/data-analyst/projects/1)

**Comment by thedatadavis** [comment]
> **Presentation**
> 
> * Be intentional about really looking at the camera when you're speaking to students, vs looking away at your other screen when you're screen sharing

_This is true. Let's punt on cleaning this up until we finalize content (I need to improve my office setup for delivering to a group of people)_ @emilybandfield 

> * Clearer separation of times when you're instructing vs letting students work on their own. I found myself distracted when trying to complete the task if you started talking again before I was finished :)

_Yeah, I know this was rough. It's the No. 1 thing I'll focus on improving in our next session_

> * Figure out a way for students to let you know they've completed a task. Maybe it is just everyone saying "I'm finished" or maybe we get creative to make it more streamlined especially when there are more people at once.

_I've created an issue for this; would love your input on what's helpful over the long run. For now, verbal affirmation should suffice_ #6

> * Provide plenty of specific opportunities for students to ask questions, so they don't feel like they're interrupting "Does anyone have any questions before we move on?"

_Definitely. I'm including this in the "be clear about separation between demonstration and hands-on" feedback_

**Comment by thedatadavis** [comment]
> You don't suck! I learned things!

Thank you for this feedback -- I'll keep the self-deprecation to a minimum lol
